### ISSUE TITLE
bug: transactions sent to self not handled well in UI

### ISSUE THREAD

**Issue by dated** [ArdentHQ/arkscan#411]
https://live.arkscan.io/addresses/AZm9LxRGH2RugWbCPk4t38zsAu5gzhmmns

<img width="1189" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/6547002/5467ab46-d866-4c76-a1e7-9822f403bfd2">

the transaction amount of the first two listed transactions on this wallet is `0.00000001` each, yet the first amount is truncated and displayed as `0.00`, with the amounts in the respective tooltips differing in precision as well.

<img width="132" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/6547002/bdc9e177-886b-4d95-a76d-580d94d5a75c">
 <img width="143" alt="image" src="https://github.com/ArdentHQ/arkscan/assets/6547002/aa58e65f-3f9c-4b78-b458-3acede80b484">

**Comment by ItsANameToo** [comment]
the reason that one shows as `0.00` is because it's sent to the same address ("sent to self"). Currently the UI does not distinguish that from a regular outgoing transaction, which is confusing. We'll improve that in a future release
